//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CADAplicacion.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-LQRDQC9;Initial Catalog=AplicacionComercial;Integrated Securi" +
            "ty=True;Encrypt=True;TrustServerCertificate=True")]
        public string AplicacionComercialConnectionString {
            get {
                return ((string)(this["AplicacionComercialConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-2F9PCG5\\SQLEXPRESS;Initial Catalog=AplicacionComercial;Integr" +
            "ated Security=True")]
        public string AplicacionComercialConnectionString1 {
            get {
                return ((string)(this["AplicacionComercialConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-LBAH3CV;Initial Catalog=AplicacionComercial;Integrated Securi" +
            "ty=True;Encrypt=True;TrustServerCertificate=True")]
        public string AplicacionComercialConnectionString2 {
            get {
                return ((string)(this["AplicacionComercialConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-B8TVDFB\\SQLEXPRESS;Initial Catalog=AplicacionComercial;Integr" +
            "ated Security=True;TrustServerCertificate=True")]
        public string AplicacionComercialConnectionString3 {
            get {
                return ((string)(this["AplicacionComercialConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-8NC4E4P;Initial Catalog=AplicacionComercial;Integrated Securi" +
            "ty=True;TrustServerCertificate=True")]
        public string AplicacionComercialConnectionString4 {
            get {
                return ((string)(this["AplicacionComercialConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SOFTSIN;Initial Catalog=AplicacionComercial;Integrated Security=True;" +
            "TrustServerCertificate=True")]
        public string AplicacionComercialConnectionString6 {
            get {
                return ((string)(this["AplicacionComercialConnectionString6"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-B8TVDFB\\SQLEXPRESS;Initial Catalog=AplicacionComercial;User I" +
            "D=sa;Password=123;Encrypt=True;TrustServerCertificate=True")]
        public string AplicacionComercialConnectionString5 {
            get {
                return ((string)(this["AplicacionComercialConnectionString5"]));
            }
        }
    }
}
